### ISSUE TITLE
Font weight of some italics can not be modified

### ISSUE THREAD

**Issue by timjackleus** [catppuccin/nvim#107]
Thank you for this amazing theme! 
I'm trying to figure out how to make values of properties "less bold". This is how it looks today:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/5394335/153760045-854d889b-ec73-47e6-b4fa-ee660b6babee.png">

My terminal is Alacritty with the following nerd font:
```
font:
  normal:
    family: BlexMono Nerd Font Mono
    style: Text

  bold:
    family: BlexMono Nerd Font Mono
    style: SemiBold

  italic:
    family: BlexMono Nerd Font Mono
    style: Italic

```

In the screenshot above, the font I have set for italics is being used for comments, keys etc. but for values it's extra bold somehow and it seems like nothing in the alacritty settings can change that. Trying other fonts leave me with the same result, normal commets but extra bold values.
