### ISSUE TITLE
I want the theme to work in spacevim

### ISSUE THREAD

**Issue by 91hm** [catppuccin/nvim#646]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Ex. I'm always frustrated when [...]. My workflow is like this [...]

Hi everyone, I am new to SpaceVim, and I am trying to install this theme:
https://gitlab.com/SpaceVim/SpaceVim

I went through the documentation using the [[custom_plugin]] syntax, but I can't seem to get this working. The theme is installed; I added the layer colorscheme, but I obtained some sort of weird colors, and I think the theme is falling back to some default.

Am I wrong in expecting to be able to install from that repo? How would you do that in your config.toml?

Thank you for your help!

**Describe the solution you'd like**
I use spacevim and I would love to use your theme but don't know how to make it work. Can you help me

**Describe alternatives you've considered**

**Additional context**

**Comment by nullchilly** [comment]
Catppuccin requires true color, add this to your configuration:

```toml
[options]
    # true colors
    enable_guicolors = true
```

![image](https://github.com/catppuccin/nvim/assets/56817415/7bfc3227-e1f0-42cf-8223-49e2d65438a8)

Here is the full config for reference (Added catppuccin to the [dark_powered.toml](https://gitlab.com/SpaceVim/SpaceVim/blob/master/mode/dark_powered.toml)

```toml
#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "catppuccin"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[custom_plugins]]
  repo = "catppuccin/nvim"
  merged = 0
```
